use serviceDishes

select * from category_entity
insert into category_entity (name) values ('Frutas y verduras'),('Cereales integrales'),('Carne y legumbres'),('Leche y productos lácteos'),('Grasas y aceites')

select * from campus_entity
insert into campus_entity (name) values ('Medellín'),('Sabaneta'),('Bello'),('Sabaneta'),('Envigado')

SELECT * FROM dish_entity
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Ceviche de Camarones', 18000, 'Delicioso ceviche de camarones', 'https://url_imagenes.com/ceviche.jpg', 'Comida de mar', true, 'Medellín')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Bandeja Paisa', 24000, 'Plato típico antioqueño', 'https://url_imagenes.com/bandeja_paisa.jpg', 'Comida típica', true, 'Envigado')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Sushi Variado', 28000, 'Sushi fresco y variado', 'https://url_imagenes.com/sushi.jpg', 'Comida de mar', true, 'Bello')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Paisa Burger', 15000, 'Hamburguesa estilo paisa', 'https://url_imagenes.com/paisa_burger.jpg', 'Hamburguesas', true, 'Itagüí')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Cazuela de Frijoles', 12000, 'Deliciosa cazuela de frijoles', 'https://url_imagenes.com/cazuela_frijoles.jpg', 'Comida típica', false, 'Sabaneta')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Pizza Vegetariana', 18000, 'Pizza con ingredientes frescos', 'https://url_imagenes.com/pizza_vegetariana.jpg', 'Pizzas', true, 'Medellín')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Patacón con Hogao', 10000, 'Crunchy patacón con hogao', 'https://url_imagenes.com/patacon_hogao.jpg', 'Comida típica', false, 'Caldas')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Empanadas de Carne', 8000, 'Sabrosas empanadas de carne', 'https://url_imagenes.com/empanadas_carne.jpg', 'Comida rápida', true, 'Rionegro')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Arroz con Pollo', 14000, 'Clásico arroz con pollo', 'https://url_imagenes.com/arroz_pollo.jpg', 'Comida típica', false, 'La Estrella')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Churrasco Argentino', 25000, 'Saboroso churrasco argentino', 'https://url_imagenes.com/churrasco_argentino.jpg', 'Carnes', true, 'Copacabana')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Ceviche de Pescado', 16000, 'Fresco ceviche de pescado', 'https://url_imagenes.com/ceviche_pescado.jpg', 'Comida de mar', true, 'Medellín')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Ajiaco Santafereño', 20000, 'Delicioso ajiaco bogotano', 'https://url_imagenes.com/ajiaco.jpg', 'Comida típica', true, 'Envigado')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Nigiri de Salmón', 26000, 'Nigiri de salmón fresco', 'https://url_imagenes.com/nigiri_salon.jpg', 'Comida de mar', true, 'Bello')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Hamburguesa BBQ', 14000, 'Hamburguesa con salsa BBQ', 'https://url_imagenes.com/hamburguesa_bbq.jpg', 'Hamburguesas', true, 'Itagüí')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Sancocho Antioqueño', 12000, 'Sancocho de la región', 'https://url_imagenes.com/sancocho.jpg', 'Comida típica', false, 'Sabaneta')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Pizza Pepperoni', 19000, 'Pizza clásica de pepperoni', 'https://url_imagenes.com/pizza_pepperoni.jpg', 'Pizzas', true, 'Medellín')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Chicharrón con Arepa', 9000, 'Chicharrón con arepa antioqueña', 'https://url_imagenes.com/chicharron_arepa.jpg', 'Comida típica', false, 'Caldas')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Pastel de Pollo', 8500, 'Pastel relleno de pollo', 'https://url_imagenes.com/pastel_pollo.jpg', 'Comida rápida', true, 'Rionegro')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Mondongo Paisa', 18000, 'Delicioso mondongo paisa', 'https://url_imagenes.com/mondongo.jpg', 'Comida típica', false, 'La Estrella')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Bife de Chorizo', 23000, 'Bife de chorizo a la parrilla', 'https://url_imagenes.com/bife_chorizo.jpg', 'Carnes', true, 'Copacabana')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Ceviche Mixto', 22000, 'Ceviche con variedad de mariscos', 'https://url_imagenes.com/ceviche_mixto.jpg', 'Comida de mar', true, 'Medellín')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Arepas Paisas', 8000, 'Arepas rellenas estilo paisa', 'https://url_imagenes.com/arepas_paisas.jpg', 'Comida típica', true, 'Envigado')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Tataki de Atún', 30000, 'Tataki de atún fresco', 'https://url_imagenes.com/tataki_atun.jpg', 'Comida de mar', true, 'Bello')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Parrillada Paisa', 32000, 'Parrillada típica antioqueña', 'https://url_imagenes.com/parrillada_paisa.jpg', 'Carnes', true, 'Itagüí')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Sopa de Frijoles', 11000, 'Sopa caliente de frijoles', 'https://url_imagenes.com/sopa_frijoles.jpg', 'Comida típica', false, 'Sabaneta')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Pizza Hawaiana', 20000, 'Pizza con piña y jamón', 'https://url_imagenes.com/pizza_hawaiana.jpg', 'Pizzas', true, 'Medellín')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Tamales Antioqueños', 9500, 'Tamales tradicionales', 'https://url_imagenes.com/tamales_antioquenos.jpg', 'Comida típica', false, 'Caldas')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Perro Caliente', 7000, 'Clásico perro caliente', 'https://url_imagenes.com/perro_caliente.jpg', 'Comida rápida', true, 'Rionegro')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Mute Santandereano', 14000, 'Mute típico de Santander', 'https://url_imagenes.com/mute.jpg', 'Comida típica', true, 'La Estrella')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Picada Antioqueña', 25000, 'Deliciosa picada antioqueña', 'https://url_imagenes.com/picada_antioquena.jpg', 'Comida típica', false, 'Copacabana')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Ceviche de Pulpo', 20000, 'Ceviche con pulpo fresco', 'https://url_imagenes.com/ceviche_pulpo.jpg', 'Comida de mar', true, 'Medellín')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Lechona Tolimense', 26000, 'Lechona típica del Tolima', 'https://url_imagenes.com/lechona_tolimense.jpg', 'Comida típica', true, 'Envigado')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Tempura de Camarones', 21000, 'Camarones tempura crujientes', 'https://url_imagenes.com/tempura_camarones.jpg', 'Comida de mar', true, 'Bello')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Hamburguesa de Pollo', 13000, 'Hamburguesa con pollo a la parrilla', 'https://url_imagenes.com/hamburguesa_pollo.jpg', 'Hamburguesas', true, 'Itagüí')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Mazamorra Antioqueña', 12000, 'Mazamorra típica antioqueña', 'https://url_imagenes.com/mazamorra.jpg', 'Comida típica', false, 'Sabaneta')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Pizza Cuatro Quesos', 22000, 'Pizza con cuatro tipos de queso', 'https://url_imagenes.com/pizza_cuatro_quesos.jpg', 'Pizzas', true, 'Medellín')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Ajiaco Cundiboyacense', 18000, 'Ajiaco típico de Cundinamarca', 'https://url_imagenes.com/ajiaco_cundiboyacense.jpg', 'Comida típica', false, 'Caldas')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Sandwich de Pollo', 8500, 'Sandwich de pollo y vegetales', 'https://url_imagenes.com/sandwich_pollo.jpg', 'Comida rápida', true, 'Rionegro')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Fritanga Paisa', 19000, 'Fritanga típica antioqueña', 'https://url_imagenes.com/fritanga_paisa.jpg', 'Comida típica', false, 'La Estrella')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Lomo de Res', 27000, 'Lomo de res a la parrilla', 'https://url_imagenes.com/lomo_res.jpg', 'Carnes', true, 'Copacabana')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Poke Bowl', 20000, 'Poke bowl con salmón y aguacate', 'https://url_imagenes.com/poke_bowl.jpg', 'Comida de mar', true, 'Medellín')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Arepas Rellenas', 9500, 'Arepas rellenas de queso y carne', 'https://url_imagenes.com/arepas_rellenas.jpg', 'Comida típica', true, 'Envigado')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Sashimi de Salmón', 32000, 'Sashimi de salmón fresco', 'https://url_imagenes.com/sashimi_salon.jpg', 'Comida de mar', true, 'Bello')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Perro Paisa', 8000, 'Perro caliente con chorizo antioqueño', 'https://url_imagenes.com/perro_paisa.jpg', 'Comida rápida', true, 'Itagüí')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Caldo de Costilla', 11000, 'Caldo de costilla caliente', 'https://url_imagenes.com/caldo_costilla.jpg', 'Comida típica', false, 'Sabaneta')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Pizza Margherita', 18000, 'Pizza margherita clásica', 'https://url_imagenes.com/pizza_margherita.jpg', 'Pizzas', true, 'Medellín')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Tamal Tolimense', 9000, 'Tamal típico del Tolima', 'https://url_imagenes.com/tamal_tolimense.jpg', 'Comida típica', false, 'Caldas')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Hot Dog Americano', 7500, 'Hot dog estilo americano', 'https://url_imagenes.com/hot_dog_americano.jpg', 'Comida rápida', true, 'Rionegro')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Mazamorra Santandereana', 13000, 'Mazamorra típica de Santander', 'https://url_imagenes.com/mazamorra_santandereana.jpg', 'Comida típica', true, 'La Estrella')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Costillas BBQ', 24000, 'Costillas a la BBQ', 'https://url_imagenes.com/costillas_bbq.jpg', 'Carnes', true, 'Copacabana')
INSERT INTO dish_entity (name, price, description, url_image, category, active, campus) VALUES ('Ceviche de Calamar', 21000, 'Ceviche con calamar fresco', 'https://url_imagenes.com/ceviche_calamar.jpg', 'Comida de mar', true, 'Medellín')


